### ISSUE TITLE
No RSS?

### ISSUE THREAD

**Issue by sbkg0002** [PrivateCaller/ytdl-current-video-archiver#1]
Hi!

Thanks for creating this! Do you know what is going wrong?

```
$ python3 ytdl-current-video-archiver.py -f feeds.txt -v 2 
-Initialized.-
-The current video cache file doesn't exist. It will be recreated.-
-Getting RSS feeds...-
Got feed https://www.youtube.com/feeds/videos.xml?channel_id=Dutchtuber2 from https://www.youtube.com/channel/Dutchtuber2.
-Checking current video cache...-
Parsing feed https://www.youtube.com/feeds/videos.xml?channel_id=Dutchtuber2...
Traceback (most recent call last):
  File "/Users/me/git/github.com/PrivateCaller/ytdl-current-video-archiver/ytdl-current-video-archiver.py", line 171, in <module>
    YouTubeDL_Current_Video_Archiver(arg.feed_file, arg.additional_urls, arg.output, arg.current_videos_cache_file, arg.video_depth, arg.downloader, arg.downloader_args).do_cycle()
  File "/Users/me/git/github.com/PrivateCaller/ytdl-current-video-archiver/ytdl-current-video-archiver.py", line 117, in do_cycle
    self.check_current_video_cache()
  File "/Users/me/git/github.com/PrivateCaller/ytdl-current-video-archiver/ytdl-current-video-archiver.py", line 65, in check_current_video_cache
    video = feed.entries[video]
            ~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range
            ~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range
```

**Comment by PrivateCaller** [comment]
I'll take a look at it tonight.

**Comment by PrivateCaller** [comment]
@sbkg0002 Is the video depth you entered greater than the number of videos on the channel? The script didn't account for that, but it should be fixed in the latest commit.
